What is a feature? feature is an individual measurable property or characteristic of a phenomenon

In simple terms, its process of extracting meaningful information from the raw text data and make it useable for the machine learning algorithm.
getting the system to recongise the cateogries and what are the characteristics within the text , including the criteria.

Example : Extracting news data with different categories such as news and sports , where you are train the model to predict the news categories

Explain the three plillars, gathering the data (shows as diagramatic presentation)




whaat is Scikit-Learn is a free machine learning library for Python.
It supports both supervised(labelled data) and unsupervised machine learning(unlabelled data), providing diverse algorithms for classification, regression, clustering, and dimensionality reduction.
The library is built using many libraries you may already be familiar with, such as NumPy and SciPy.
It also plays well with other libraries, such as Pandas and Seaborn.




What is a vector?
A vector in a simple term can be considered as a single-dimensional array. With respect to Python, a vector is a one-dimensional array of lists


Syntax:
numpy.array(list)

In [ ]:
import numpy as np

lst = [10,20,30,40,50]

vctr = np.array(lst)

vctr = np.array(lst)

print("Vector created from a list:")
print(vctr)

Vector created from a list:
[10 20 30 40 50]


In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,2,3,4,5]

vctr1 = np.array(lst1)

vctr2= np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_mul = vctr1*vctr2
print("Multiplication of two vectors: ",vctr_mul)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Multiplication of two vectors:  [ 10  40  90 160 250]


In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,2,3,4,5]


vctr1 = np.array(lst1)

vctr2= np.array(lst2)


print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_add = vctr1+vctr2
print("Addition of two vectors: ",vctr_add)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Addition of two vectors:  [11 22 33 44 55]


What is supervised and unsupervised machine learning ?



In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [10,20,30,40,50]

vctr1 = np.array(lst1)

vctr2= np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_div = vctr1/vctr2
print("Division of two vectors: ",vctr_div)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[10 20 30 40 50]
Division of two vectors:  [1. 1. 1. 1. 1.]


In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,1,1,1,1]


vctr1 = np.array(lst1)

vctr2= np.array(lst2)


print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_dot = vctr1.dot(vctr2)
print("Dot product of two vectors: ",vctr_dot)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 1 1 1 1]
Dot product of two vectors:  150


In [ ]:
pip install scikit-learn

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import NMF, PCA
from sklearn.manifold import TSNE
import numpy as np
import spacy

# file_path = "flood_news.txt"

# with open(file_path, 'r') as file:
#     text = file.read()

# Input text
text = "Natural Language Processing (NLP) is a subfield of computer science, " \
       "artificial intelligence, and computational linguistics concerned with " \
       "the interactions between computers and human (natural) languages. " \
       "It focuses on how to program computers to process and analyze large " \
       "amounts of natural language data."

# Tokenize the text
tokens = word_tokenize(text)
print(len(tokens))
print(tokens[:20])

50
['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'subfield', 'of', 'computer', 'science', ',', 'artificial', 'intelligence', ',', 'and', 'computational', 'linguistics', 'concerned']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Count Vectorizer:
Machines cannot understand characters and words. So when dealing with text data we need to represent it in numbers to be understood by the machine. Countvectorizer is a method to convert text to numerical data

example:

text = [‘Hello my name is james, this is my python notebook’]

Where it can be used?

Countvectorizer makes it easy for text data to be used directly in machine learning and deep learning models such as text classification.

In [ ]:
# CountVectorizer
count_vec = CountVectorizer()
X_count = count_vec.fit_transform([text])
print('CountVectorizer:')
print(count_vec.get_feature_names_out()[:10])
print(count_vec.get_feature_names_out())
print(X_count.toarray()[0])
print(X_count.toarray()[0][:10])

CountVectorizer:
['amounts' 'analyze' 'and' 'artificial' 'between' 'computational'
 'computer' 'computers' 'concerned' 'data']
['amounts' 'analyze' 'and' 'artificial' 'between' 'computational'
 'computer' 'computers' 'concerned' 'data' 'focuses' 'how' 'human'
 'intelligence' 'interactions' 'is' 'it' 'language' 'languages' 'large'
 'linguistics' 'natural' 'nlp' 'of' 'on' 'process' 'processing' 'program'
 'science' 'subfield' 'the' 'to' 'with']
[1 1 3 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 3 1 2 1 1 1 1 1 1 1 2 1]
[1 1 3 1 1 1 1 2 1 1]


TF-IDF stands for Term Frequency Inverse Document Frequency of records. It can be defined as the calculation of how relevant a word in a series or corpus is to a text. The meaning increases proportionally to the number of times in the text a word appears but is compensated by the word frequency in the corpus (data-set).

tf(t,d) = count of t in d / number of words in d


df(t) = occurrence of t in documents


df(t) = N(t)
where
df(t) = Document frequency of a term t
N(t) = Number of documents containing the term t

In [ ]:
# TF-IDF
tfidf_vec = TfidfVectorizer()
X_tfidf = tfidf_vec.fit_transform([text])
print('TF-IDF:')
print(tfidf_vec.get_feature_names_out())
# length of the whole text --> confirm it
print(X_tfidf.toarray()[0])

TF-IDF:
['100' '20' '200' '2016' '56' '70' '700' 'about' 'abruptly' 'across'
 'actions' 'added' 'advanced' 'after' 'against' 'agencies' 'alerts' 'all'
 'alone' 'already' 'also' 'altitudes' 'an' 'and' 'any' 'are' 'area'
 'around' 'as' 'at' 'attribute' 'authorities' 'authority' 'autonomous'
 'avalanches' 'banks' 'bbc' 'be' 'because' 'become' 'becomes' 'becoming'
 'been' 'begin' 'being' 'borders' 'boulders' 'buildings' 'bureaucracy'
 'burst' 'bursting' 'bursts' 'but' 'by' 'campaigner' 'campaigners' 'can'
 'cause' 'caused' 'causing' 'central' 'centre' 'certainly' 'changes'
 'characterised' 'checking' 'china' 'chungthang' 'climate' 'cloudburst'
 'cloudbursts' 'collapsed' 'collapses' 'commission' 'communities'
 'concentrated' 'confirmed' 'constant' 'construction' 'could' 'cryosphere'
 'dam' 'damage' 'dams' 'dangerous' 'deadly' 'decades' 'defence' 'delhi'
 'department' 'deploy' 'details' 'development' 'dhiren' 'did' 'didn'
 'died' 'director' 'disaster' 'do' 'down' 'downstream' 'drew' 'due'
 '

word embedding calculate how it related to meaning
e.g : queen and king
e.g : flood and disaster

In [ ]:
# Word embeddings (using spaCy)
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp(text)
embeddings = [token.vector for token in doc]
print('Word embeddings:')
print(len(embeddings))

Word embeddings:
1199


what is cosine similaity ?
  the word counts can be represented as a vector
  to find the similarities these two sets of words or documents

with cosime similarity
 a= {flood, natural}
 b= {the, natural}



In [ ]:
# Compare similarities using cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

# Similarity between "flood" and "disaster"
word1 = "flood"
word2 = "disaster"
embedding_sim = cosine_similarity(embeddings[tokens.index(word1)].reshape(1, -1),
                                   embeddings[tokens.index(word2)].reshape(1, -1))
tfidf_sim = cosine_similarity(X_tfidf[:, tfidf_vec.vocabulary_[word1]].reshape(1, -1),
                               X_tfidf[:, tfidf_vec.vocabulary_[word2]].reshape(1, -1))
print(f'Similarity between "{word1}" and "{word2}" using word embeddings:', embedding_sim[0][0])
print(f'Similarity between "{word1}" and "{word2}" using TF-IDF:', tfidf_sim[0][0])


Similarity between "flood" and "disaster" using word embeddings: 0.47615007
Similarity between "flood" and "disaster" using TF-IDF: 1.0


The bag-of-words model is used to extract features from the text by disregarding the grammar and order of words by keeping their multiple occurrences. It is represented as a bag of its words and here the occurrence of each word is used as a feature for the training classifier.

creating unique values for each words with the scoring part

“it” = 1
“was” = 1
“the” = 1
“best” = 1
“of” = 1
“times” = 1
“worst” = 0
“age” = 0
“wisdom” = 0
“foolishness” = 0

example a= "it was the worst of times"
        a=['1','1','1','1','1']

In [ ]:
# Bag of words
bag_of_words = {word: tokens.count(word) for word in set(tokens)}
print('Bag of words:\n')
print(list(bag_of_words.items()))

Bag of words:


 [('warned', 1), ('unstable', 1), ('temperatures', 1), ('feeds', 1), ('land', 1), ('certainly', 1), ('warnings', 2), ('Jacob', 1), ('fast-melting', 1), ('Perhaps', 1), ('together', 1), ('National', 1), ('remains', 2), ('Miriam', 1), ('20', 1), ('warming', 1), ('disaster', 2), ('is', 4), ('down', 1), (',', 45), ('filling', 1), ('(', 6), ('also', 4), ('actions', 1), ('said', 4), ('other', 3), ('them', 1), ('its', 2), ('event', 1), ('time', 4), ('say', 7), ('already', 2), ('will', 2), ('local', 2), ('did', 5), ('leading', 1), ('have', 10), ('caused', 2), ('small', 1), ('for', 8), ('science', 1), ('involved', 2), ('against', 1), ('Shrestha', 1), ('Meanwhile', 1), ('risk-mitigating', 1), ('many', 1), ('agencies', 2), ('were', 2), ('number', 1), ('advanced', 1), ('``', 7), ('56', 1), ('from', 5), ('glaciology', 1), ('question', 1), ('expanded', 1), ('by', 3), ('several', 2), ('helping', 1), ('cloudbursts', 1), ('geological', 1), ('increase', 1), ('characterised', 1), ('since'

two gram is a two word combinations that occurs in the text
example "i am"
three gram phrase
example "this is killing"

Where can it be used ? sentence predicition of a text
eg autocomplete text in search engines


In [ ]:
# Bag of n-grams
n = 2
ngrams = [tuple(tokens[i:i+n]) for i in range(len(tokens)-n+1)]
bag_of_ngrams = {ngram: ngrams.count(ngram) for ngram in set(ngrams)}
print('Bag of n-grams:')
print(list(bag_of_ngrams.items()))

Bag of n-grams:
[(('been', 'issued'), 1), (('fast-melting', 'glaciers'), 1), (('dangerous', '.'), 2), (('so', 'long'), 1), (('work', 'was'), 1), (('up', 'to'), 1), (('hazards', ','), 1), (('system', 'was'), 1), ((',', 'and'), 2), (('is', 'so'), 1), (('by', 'heavy'), 1), (('also', 'means'), 1), (('Scientists', 'are'), 1), (('dams', 'downstream'), 1), (('north-east', 'state'), 1), (('was', 'a'), 1), (('three', 'decades'), 1), (('military', 'sensitivities'), 1), (('the', 'edge'), 1), (('moved', 'exceptionally'), 1), (('the', 'system'), 1), ((',', 'a'), 4), (('people', '-'), 1), (('thawing', 'of'), 1), (('that', 'there'), 1), (('started', 'hitting'), 1), (('20', 'are'), 1), (('that', 'make'), 1), (('and', 'experts'), 1), (('permanently', 'frozen'), 1), (('resulting', 'in'), 1), (('while', 'others'), 1), (('triggered', 'by'), 1), (('on', 'mountains'), 1), (('had', 'been'), 1), (('around', 'all'), 1), (('checking', 'how'), 1), (('Sikkim', 'shows'), 1), (('of', 'several'), 1), (('water', 'to'

HashingVectorizer converts a collection of text documents to a matrix of token occurrences. This text vectorizer implementation uses the hashing trick to find the token stream name to feature integer index mapping.


What is the difference between hashing and count vectorizer?

with hashing vectorizer, it shows the position of the text whether it occurs in first or middle. The position can tell where the text was placed whereas the count vectorizer does not perform this functionality

In [ ]:
# HashingVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
hash_vec = HashingVectorizer(n_features=100)
X_hash = hash_vec.fit_transform([text])
print('HashingVectorizer:')
print(X_hash.shape, X_hash.toarray()[0])

HashingVectorizer:
(1, 100) [ 0.02102237 -0.05255593 -0.02102237  0.06306712 -0.06306712 -0.02102237
 -0.02102237 -0.01051119  0.01051119  0.02102237  0.12613423  0.01051119
 -0.02102237 -0.02102237  0.04204474  0.03153356 -0.01051119  0.
  0.16817897 -0.04204474  0.04204474  0.03153356 -0.02102237 -0.01051119
  0.         -0.05255593  0.         -0.03153356 -0.1471566  -0.05255593
  0.         -0.01051119 -0.01051119 -0.04204474  0.03153356  0.05255593
  0.08408949  0.06306712  0.02102237  0.06306712  0.         -0.04204474
 -0.0735783   0.0735783   0.         -0.16817897  0.         -0.02102237
  0.04204474  0.02102237  0.01051119  0.04204474 -0.05255593  0.
  0.         -0.0735783   0.03153356  0.         -0.56760404 -0.02102237
 -0.10511186 -0.01051119  0.06306712 -0.10511186  0.          0.02102237
  0.04204474 -0.01051119  0.01051119 -0.04204474  0.          0.01051119
 -0.02102237 -0.01051119  0.01051119  0.10511186  0.01051119  0.04204474
 -0.05255593  0.02102237 -0.01051119 -0

Each document is made up of various words, and each topic also has various words belonging to it. Its is one of the topic modelling.


what is parts of speech tagging?

Part-of-speech tagging is the process of assigning a part of speech to each word in a sentence. The most common parts of speech are noun, verb, adjective, adverb, pronoun, preposition, and conjunction. There are also a few less common ones, such as interjection and article.

Why ?

when you are trying to parse a sentence or when you are trying to determine the meaning of a word in context.


Different cateogries:

Noun (NN): A person, place, thing, or idea
Verb (VB): An action or occurrence
Adjective (JJ): A word that describes a noun or pronoun
Adverb (RB): A word that describes a verb, adjective, or other adverb
Pronoun (PRP): A word that takes the place of a noun
Conjunction (CC): A word that connects words, phrases, or clauses
Preposition (IN): A word that shows a relationship between a noun or pronoun and other elements in a sentence
Interjection (UH): A word or phrase used to express strong emotion

Where it can be used?

named entity recognition — This is where POS tagging can be used to identify proper nouns in a text, which can then be used to extract information about people, places, organizations, etc.


sentiment analysis — By identifying words with positive or negative connotations, POS tagging can be used to calculate the overall sentiment of a piece of text.


topic identification — By looking at which words are most commonly used together, POS tagging can help automatically identify the main topics of a document.


machine translation — In order for machines to translate one language into another, they need to understand the grammar and structure of the source language. POS tagging can be used to provide this understanding, allowing for more accurate translations.


question answering — When trying to answer questions based on documents, machines need to be able to identify the key parts of speech in the question in order to correctly find the relevant information in the text.

In [ ]:
nltk.download('averaged_perceptron_tagger')

# Tokenize the text into sentences and words
sentences = nltk.sent_tokenize(text)
words = [nltk.word_tokenize(sentence) for sentence in sentences]

# Perform POS tagging on the words
pos_tags = [nltk.pos_tag(sentence) for sentence in words]

# Print the POS tags
for sentence in pos_tags:
    print(sentence)

[('A', 'DT'), ('deadly', 'JJ'), ('flash', 'NN'), ('flood', 'NN'), ('in', 'IN'), ('the', 'DT'), ('north-east', 'JJ'), ('state', 'NN'), ('of', 'IN'), ('Sikkim', 'NNP'), ('shows', 'NNS'), ('why', 'WRB'), ('India', 'NNP'), ('urgently', 'RB'), ('needs', 'VBZ'), ('to', 'TO'), ('install', 'VB'), ('advanced', 'JJ'), ('early', 'JJ'), ('warning', 'NN'), ('systems', 'NNS'), ('for', 'IN'), ('its', 'PRP$'), ('dangerous', 'JJ'), ('glacial', 'JJ'), ('lakes', 'NNS'), (',', ','), ('experts', 'NNS'), ('say', 'VBP'), ('.', '.')]
[('At', 'IN'), ('least', 'JJS'), ('70', 'CD'), ('people', 'NNS'), ('-', ':'), ('including', 'VBG'), ('nine', 'CD'), ('soldiers', 'NNS'), ('-', ':'), ('have', 'VBP'), ('died', 'VBN'), (',', ','), ('and', 'CC'), ('more', 'JJR'), ('than', 'IN'), ('100', 'CD'), ('others', 'NNS'), ('are', 'VBP'), ('missing', 'VBG'), ('after', 'IN'), ('South', 'NNP'), ('Lhonak', 'NNP'), (',', ','), ('a', 'DT'), ('glacial', 'JJ'), ('lake', 'NN'), ('in', 'IN'), ('the', 'DT'), ('Himalayas', 'NNP'), (',', 

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


UNSUPERVISED MACHINE LEARNING STARTS HERE

In [ ]:
# Latent Dirichlet Allocation (LDA)
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=10, random_state=42)
X_lda = lda.fit_transform(X_tfidf)
print('LDA:')
print(X_lda)

LDA:
[[0.00893421 0.00893421 0.00893421 0.00893421 0.00893421 0.00893421
  0.00893421 0.00893421 0.9195921  0.00893421]]


What is Supervised and Unsupervised machine learning algorithm?


Non-negative Matrix Factorization or NMF is a method used to factorize a non-negative matrix, X, into the product of two lower rank matrices, A and B, such that AB approximates an optimal solution of X.



This technique is mostly used in recommendation systems or text mining

It can produce meaningful patterns, topics, and themes.

In [ ]:
# Non-negative Matrix Factorization (NMF)
nmf = NMF(n_components=10, random_state=42)
X_nmf = nmf.fit_transform(X_tfidf)
print('NMF:')
print(X_nmf)

NMF:
[[0.18255958 0.06329122 0.0295038  0.08910936 0.04951805 0.09344841
  0.         0.04422256 0.02907843 0.0347387 ]]
